import type { PasswordGeneratorOption } from './option.interface';

const DEFAULT_PASSWORD_GENERATOR_OPTION_DIGITS = true;
const DEFAULT_PASSWORD_GENERATOR_OPTION_LENGTH = 32;
const DEFAULT_PASSWORD_GENERATOR_OPTION_LOWERCASES = true;
const DEFAULT_PASSWORD_GENERATOR_OPTION_UPPERCASES = true;
const DEFAULT_PASSWORD_GENERATOR_OPTION_SYMBOLS = true;

const DEFAULT_PASSWORD_GENERATOR_OPTION: PasswordGeneratorOption = {
	length: DEFAULT_PASSWORD_GENERATOR_OPTION_LENGTH,
	digits: DEFAULT_PASSWORD_GENERATOR_OPTION_DIGITS,
	lowercases: DEFAULT_PASSWORD_GENERATOR_OPTION_LOWERCASES,
	uppercases: DEFAULT_PASSWORD_GENERATOR_OPTION_UPPERCASES,
	symbols: DEFAULT_PASSWORD_GENERATOR_OPTION_SYMBOLS,
};

export { DEFAULT_PASSWORD_GENERATOR_OPTION };
