const NUMBER_CHARACTERS = '0123456789';
const SYMBOL_CHARACTERS = '[](){}@#$%&*~+-_=!';
const LOWER_CHARACTERS = 'abcdefghijklmnopqrstuvwxyz';
const UPPER_CHARACTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

export {
	NUMBER_CHARACTERS,
	SYMBOL_CHARACTERS,
	LOWER_CHARACTERS,
	UPPER_CHARACTERS,
};
